name: Build and Test

on:
  push:
    branches: [ test/v1.0.0 ]
  pull_request:
    branches: [ test/v1.0.0 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [host-app, products-remote, basket-remote]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          
      - name: Build ${{ matrix.app }}
        run: |
          cd ${{ matrix.app }}
          npm ci
          npm run build
          
      - name: Run Tests
        run: |
          cd ${{ matrix.app }}
          npm test 